export type Page =
    | "home"
    | "login"
    | "signup"
    | "dashboard"
    | "findAccount"
    | "notices"
    | "resetPassword"
    | "bids"
    | "analytics"
    | "summary"
    | "cart"
    | "notifications"
    | "chatbot"
    | "profile";
